package standardmap;

import java.util.Timer;
import java.util.TimerTask;
import java.awt.*;  
import java.awt.event.*;  
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame{

    public static double K;
    public static int N;
    public static int counter;
	
    public static final int PANEL_SIZE = 200;
    public static final int SCREEN_WIDTH = 1000;
    public static final int OFFSET_X = 30;
    public static final int OFFSET_Y = 30;
    public static final int TITLE_SIZE = 60;
    
    public static final int GRAPH_SIZE = SCREEN_WIDTH - 2*PANEL_SIZE - 2*OFFSET_X;
    public static final int SCREEN_HEIGHT =700;
    

    public static final int GRID_SIZE = 5;

    public static boolean isSet; //check if it's set
    public static boolean isClear = true; //check if it's clear
    public static boolean isCalculate = false; //check if the calculation of Kc is in process.
    public static int numIteration= 0; //number of iterations "for each" K
    
    public static String stateOfK = "below";
    
    public Graph newGraph;
    
    public MainFrame() {    
        K = 0.45; N = 1500;
        initComponents();   
        
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        CalculatePanel = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        GraphPanel = new Graph(K,N);
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelK = new javax.swing.JLabel();
        DisplayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDisplayK = new javax.swing.JTable();
        ControlPanel = new javax.swing.JPanel();
        btnStop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DescriptionPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SetPanel = new javax.swing.JPanel();
        tf_K0 = new javax.swing.JTextField();
        LabelK0 = new javax.swing.JLabel();
        btnSet = new javax.swing.JButton();
        btnClrSet = new javax.swing.JButton();
        tf_N = new javax.swing.JTextField();
        LabelNumIterations = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Standard Map");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        TitlePanel.setBackground(new java.awt.Color(0, 0, 0));
        TitlePanel.setPreferredSize(new java.awt.Dimension(SCREEN_WIDTH,TITLE_SIZE));

        LabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("Standard Map: Critical Value of K");
        LabelTitle.setName(""); // NOI18N
        TitlePanel.add(LabelTitle);

        CalculatePanel.setBackground(new java.awt.Color(204, 204, 204));
        CalculatePanel.setPreferredSize(new java.awt.Dimension(PANEL_SIZE,80)	);

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculate Kc here");

        javax.swing.GroupLayout CalculatePanelLayout = new javax.swing.GroupLayout(CalculatePanel);
        CalculatePanel.setLayout(CalculatePanelLayout);
        CalculatePanelLayout.setHorizontalGroup(
            CalculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatePanelLayout.createSequentialGroup()
                .addGroup(CalculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatePanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        CalculatePanelLayout.setVerticalGroup(
            CalculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        GraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        GraphPanel.setToolTipText("");
        GraphPanel.setPreferredSize(new java.awt.Dimension(GRAPH_SIZE + 2*OFFSET_X,GRAPH_SIZE+2*OFFSET_Y)	);

        jLabel4.setText("0");

        jLabel6.setText("I");

        jLabel7.setText("<html>2&pi</html>");

        jLabel8.setText("<html>2&pi</html>");

        jLabel10.setText("U");

        labelK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelK.setText("K="+K);
        labelK.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelKAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
        GraphPanel.setLayout(GraphPanelLayout);
        GraphPanelLayout.setHorizontalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelLayout.createSequentialGroup()
                .addGroup(GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GraphPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(246, 246, 246)
                        .addComponent(jLabel7))
                    .addGroup(GraphPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GraphPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(GraphPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(369, 369, 369)
                        .addComponent(labelK, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        GraphPanelLayout.setVerticalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelK))
                .addGap(255, 255, 255)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addGroup(GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GraphPanelLayout.createSequentialGroup()
                        .addGroup(GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(16, 16, 16))
                    .addGroup(GraphPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
        );

        DisplayPanel.setBackground(new java.awt.Color(204, 204, 204));
        DisplayPanel.setPreferredSize(new java.awt.Dimension(PANEL_SIZE,500)	);

        tableDisplayK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "K", "below/beyond"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDisplayK.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableDisplayKAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tableDisplayK);
        if (tableDisplayK.getColumnModel().getColumnCount() > 0) {
            tableDisplayK.getColumnModel().getColumn(0).setResizable(false);
            tableDisplayK.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        ControlPanel.setBackground(new java.awt.Color(204, 204, 204));
        ControlPanel.setPreferredSize(new java.awt.Dimension(PANEL_SIZE,PANEL_SIZE)	);

        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>Calculation<br/>Control</center></html>");

        btnClear.setText("Clear Graph & Table");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html><center>Visualization<br/>Control</center></html>");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addGap(127, 127, 127))
        );

        DescriptionPanel.setBackground(new java.awt.Color(204, 204, 204));
        DescriptionPanel.setPreferredSize(new java.awt.Dimension(PANEL_SIZE, 150)	);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><center>Standard Map</center>"
            + "<BR> I<sub>n+1</sub> = I<sub>n</sub> + Ksin(U<sub>n</sub>) (mod 2&pi)"
            + "<BR> U<sub>n+1</sub> = U<sub>n</sub> + I<sub>n+1</sub> (mod 2&pi)</html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 400));

        javax.swing.GroupLayout DescriptionPanelLayout = new javax.swing.GroupLayout(DescriptionPanel);
        DescriptionPanel.setLayout(DescriptionPanelLayout);
        DescriptionPanelLayout.setHorizontalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DescriptionPanelLayout.setVerticalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        SetPanel.setBackground(new java.awt.Color(204, 204, 204));
        SetPanel.setPreferredSize(new java.awt.Dimension(PANEL_SIZE,PANEL_SIZE)	);

        tf_K0.setText(String.valueOf(K)
        );
        tf_K0.setPreferredSize(new java.awt.Dimension(8, 22));
        tf_K0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_K0ActionPerformed(evt);
            }
        });

        LabelK0.setText("K0: ");

        btnSet.setText("Set");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        btnClrSet.setText("Clear");
        btnClrSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrSetActionPerformed(evt);
            }
        });

        tf_N.setText(String.valueOf(N)
        );
        tf_N.setPreferredSize(new java.awt.Dimension(8, 22));
        tf_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NActionPerformed(evt);
            }
        });

        LabelNumIterations.setText("N:");

        javax.swing.GroupLayout SetPanelLayout = new javax.swing.GroupLayout(SetPanel);
        SetPanel.setLayout(SetPanelLayout);
        SetPanelLayout.setHorizontalGroup(
            SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SetPanelLayout.createSequentialGroup()
                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelK0)
                            .addComponent(LabelNumIterations, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_N, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_K0, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SetPanelLayout.createSequentialGroup()
                        .addComponent(btnSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClrSet)))
                .addGap(23, 23, 23))
        );
        SetPanelLayout.setVerticalGroup(
            SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_K0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelK0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_N, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumIterations))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClrSet)
                    .addComponent(btnSet))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DescriptionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(CalculatePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(ControlPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addComponent(SetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalculatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, Short.MAX_VALUE))
                    .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)))
        );

        ControlPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_K0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_K0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_K0ActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        
        if(isSet){
            btnSet.setEnabled(false);
            btnClrSet.setEnabled(false);
            btnCalculate.setEnabled(false);
            btnStop.setEnabled(true);

            //counter = 0;
            ((Graph)GraphPanel).setK(K);
            ((Graph)GraphPanel).setN(N);

            isCalculate = true;
            
            try{
                if(!((Graph)GraphPanel).isGraphClear() || !((Graph)GraphPanel).isTableClear()){
                    JOptionPane.showMessageDialog(null,"Graph and table must be cleared","Clear stuffs",JOptionPane.WARNING_MESSAGE);
                    tf_K0.setEditable(true);
                    tf_N.setEditable(true);

                    btnSet.setEnabled(true);
                    btnClrSet.setEnabled(true);
                    btnCalculate.setEnabled(true);
                    btnStop.setEnabled(false);

                    isSet = false;
                    isCalculate = false;
                }else if(!isSet){
                    JOptionPane.showMessageDialog(null,"Set the values before calculation","Set",JOptionPane.WARNING_MESSAGE);
                }else{
                try {
                    ((Graph)GraphPanel).estimateKc();
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }catch(OutOfMemoryError e){
                JOptionPane.showMessageDialog(null,"Number of Iterations (N) is too big","Out of Memory",JOptionPane.WARNING_MESSAGE);
                tf_K0.setEditable(true);
                tf_N.setEditable(true);

                btnSet.setEnabled(true);
                btnClrSet.setEnabled(true);
                btnCalculate.setEnabled(true);
                btnStop.setEnabled(false);

                isSet = false;
                isCalculate = false;
            }
            
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClrSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrSetActionPerformed
        // TODO add your handling code here:
        tf_K0.setEditable(true);
        tf_K0.setText(null);
        
        tf_N.setEditable(true);
        tf_N.setText(null);
        btnSet.setEnabled(true);
        
        isSet = false;
    }//GEN-LAST:event_btnClrSetActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        stopIteration();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        // TODO add your handling code here:
        
        isSet = !tf_K0.getText().isEmpty() && !tf_N.getText().isEmpty();
        try{
            if(isSet){
                K = Double.parseDouble(tf_K0.getText()); 
                N = Integer.parseInt(tf_N.getText());
                
                if(N>0 && K>=0){
                    tf_K0.setEditable(false); tf_N.setEditable(false);
                    btnSet.setEnabled(false);
                }else if(N<=0){
                    JOptionPane.showMessageDialog(null,"N must be positive","Positive N",JOptionPane.WARNING_MESSAGE);
                }else if(K<0){
                    JOptionPane.showMessageDialog(null,"K must be positive or zero","Not Negative K",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Please Set both values.","Set",JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please input positive number.","Be Positive",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSetActionPerformed

    private void tf_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null,"Do you want to clear graph and table?", "Clear Stuffs?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if(result == JOptionPane.YES_OPTION){
            btnSet.setEnabled(true);
            btnClrSet.setEnabled(true);
            btnCalculate.setEnabled(true);
            
            tf_K0.setEditable(true);
            tf_N.setEditable(true);
        
            //clear graph
            ((Graph)GraphPanel).clearGraph();
            //clear table
            DefaultTableModel model = (DefaultTableModel) tableDisplayK.getModel();
            model.setRowCount(0);
            
            btnClear.setEnabled(false);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void labelKAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_labelKAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_labelKAncestorAdded

    private void tableDisplayKAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableDisplayKAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDisplayKAncestorAdded

    private void stopIteration(){
        
        int result = JOptionPane.showConfirmDialog(null,"Do you want to stop the iteration?", "Stop?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            ((Graph)GraphPanel).stop();
           
            btnStop.setEnabled(false);
            btnClear.setEnabled(true);
            
            isSet = false;
            isCalculate = false;
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalculatePanel;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JPanel DisplayPanel;
    public static javax.swing.JPanel GraphPanel;
    private javax.swing.JLabel LabelK0;
    private javax.swing.JLabel LabelNumIterations;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel SetPanel;
    private javax.swing.JPanel TitlePanel;
    public static javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClrSet;
    private javax.swing.JButton btnSet;
    public static javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelK;
    public static javax.swing.JTable tableDisplayK;
    public static javax.swing.JTextField tf_K0;
    public static javax.swing.JTextField tf_N;
    // End of variables declaration//GEN-END:variables
}
